# Generated by Django 4.2.3 on 2023-07-21 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('cooking_time', models.PositiveIntegerField()),
                ('difficulty', models.CharField(choices=[('Easy', 'easy'), ('Medium', 'medium'), ('Intermediate', 'intermediate'), ('Hard', 'hard')], default='Easy', max_length=12)),
                ('ingredients', models.CharField(max_length=255)),
            ],
        ),
    ]
